// <auto-generated />
using Agenda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Agenda.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20220327190243_addTarefa")]
    partial class addTarefa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Agenda.Entities.Tarefa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("completa")
                        .HasColumnType("boolean");

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.Property<string>("prazo")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tarefa");
                });
#pragma warning restore 612, 618
        }
    }
}
